version: '3.8'

x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    PYTHONPATH: "/opt/app"
  volumes:
    - .:/opt/app
  working_dir: "/opt/app"

services:
  api:
    <<: *common
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: ["uvicorn", "--factory", "api.asgi:create_app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
